# Generated by Django 2.2.3 on 2019-07-28 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_name', models.CharField(max_length=120)),
                ('milk_company_category_id', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('available', models.CharField(choices=[('L', 'L'), ('ML', 'ML'), ('Bages', 'Bages')], max_length=120)),
                ('description', models.TextField()),
                ('manufacture_date', models.DateTimeField(auto_now=True)),
                ('expired_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Milk_Product',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_first_name', models.CharField(max_length=120)),
                ('user_last_name', models.CharField(max_length=120)),
                ('mobile_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('address_id', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Users',
            },
        ),
    ]
