# Generated by Django 2.2.3 on 2019-07-28 12:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=120)),
                ('country_code', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Country',
            },
        ),
        migrations.CreateModel(
            name='MilkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_category', models.CharField(choices=[('Organic', 'Organic'), ('Routine', 'Routine')], default='Routine', max_length=120)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Milk_Category',
            },
        ),
        migrations.CreateModel(
            name='MilkCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('gst_no', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\d{2}[A-Z]{5}\\d{4}[A-Z]{1}[A-Z\\d]{1}[Z]{1}[A-Z\\d]{1}$')])),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('leave_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Milk_Company',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
        migrations.AddField(
            model_name='milk',
            name='image',
            field=models.ImageField(blank=True, upload_to='prodcuts/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='milk',
            name='available',
            field=models.CharField(choices=[('L', 'L'), ('ML', 'ML'), ('Bages', 'Bages')], default='L', max_length=120),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('subscription_type', models.CharField(choices=[('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Weekend', 'Weekend')], default='Daily', max_length=120)),
                ('milk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk', to='milk.Milk')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='milk.User')),
            ],
            options={
                'verbose_name': 'Subsription',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=120)),
                ('status', models.BooleanField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.Country')),
            ],
            options={
                'verbose_name': 'State',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=120)),
                ('payment', models.IntegerField()),
                ('payment_status', models.BooleanField()),
                ('status', models.BooleanField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.Order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='milk.User')),
            ],
            options={
                'verbose_name': 'Payment',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='milk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.Milk'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='milk.User'),
        ),
        migrations.CreateModel(
            name='MilkCompanyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.MilkCategory')),
                ('milk_company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_company', to='milk.MilkCompany')),
            ],
            options={
                'verbose_name': 'Milk_Company_Category',
            },
        ),
        migrations.CreateModel(
            name='DeliveryTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='milk.User')),
            ],
            options={
                'verbose_name': 'Delivery_Time',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=120)),
                ('status', models.BooleanField()),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.State')),
            ],
            options={
                'verbose_name': 'City',
            },
        ),
    ]
