# Generated by Django 2.2.3 on 2019-07-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0002_auto_20190728_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='prodcuts/fm/%Y/%m/%d')),
                ('available', models.CharField(choices=[('L', 'L'), ('ML', 'ML'), ('Bages', 'Bages')], default='L', max_length=120)),
                ('description', models.TextField()),
                ('manufacture_date', models.DateTimeField(auto_now=True)),
                ('expired_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Farmer_Products',
            },
        ),
    ]
