# Generated by Django 2.2.3 on 2019-07-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0004_auto_20190730_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='milk_id',
        ),
    ]
