# Generated by Django 2.2.3 on 2019-07-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0007_auto_20190730_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNeedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='prodcuts/fm/%Y/%m/%d')),
                ('available', models.CharField(choices=[('L', 'L'), ('ML', 'ML'), ('Bages', 'Bages')], default='L', max_length=120)),
                ('description', models.TextField()),
                ('manufacture_date', models.DateTimeField(auto_now=True)),
                ('expired_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Daily_Need_Products',
            },
        ),
        migrations.CreateModel(
            name='DailyPCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dailyp_category', models.CharField(choices=[('Dairy', 'Dairy'), ('Bakery', 'Bakery'), ('Grocery', 'Grocery')], default='Routine', max_length=120)),
                ('d_id', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'DailyP_Category',
            },
        ),
    ]
