# Generated by Django 2.2.3 on 2019-07-30 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0008_dailyneedproduct_dailypcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyneedproduct',
            name='available',
        ),
        migrations.AddField(
            model_name='dailyneedproduct',
            name='p_category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='milk.DailyPCategory'),
            preserve_default=False,
        ),
    ]
