# Generated by Django 2.2.4 on 2019-09-21 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0010_addtocart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milk.Milk'),
        ),
    ]
