# Generated by Django 2.2.4 on 2019-09-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0011_auto_20190921_0559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='product_id',
            new_name='milk_id',
        ),
    ]
