# Generated by Django 2.2.4 on 2019-11-24 12:20

from django.db import migrations, models
import django.db.models.deletion
import milk.models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0012_auto_20190921_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default=1, upload_to=milk.models.upload_profile_photo),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='milk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk', to='milk.Milk'),
        ),
    ]
