# Generated by Django 2.2.4 on 2019-11-24 14:13

from django.db import migrations, models
import milk.models


class Migration(migrations.Migration):

    dependencies = [
        ('milk', '0013_auto_20191124_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_id',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=milk.models.upload_profile_photo),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
